Repository Mirror-Protocol/mirror-contracts, pull requests merged in 2021-05, with the labels that each got.

#31 [Feature] Improvements to collaterals
  contracts/mirror_collateral_oracle/schema/collateral_info_response.json
  contracts/mirror_collateral_oracle/schema/collateral_infos_response.json
  contracts/mirror_collateral_oracle/schema/collateral_price_response.json
  contracts/mirror_collateral_oracle/schema/config_response.json
  contracts/mirror_collateral_oracle/schema/handle_msg.json
  contracts/mirror_collateral_oracle/schema/init_msg.json
  contracts/mirror_collateral_oracle/src/contract.rs
  contracts/mirror_collateral_oracle/src/mock_querier.rs
  contracts/mirror_collateral_oracle/src/state.rs
  contracts/mirror_collateral_oracle/src/testing.rs
  contracts/mirror_collateral_oracle/tests/integration.rs
  contracts/mirror_mint/src/asserts.rs
  contracts/mirror_mint/src/contract.rs
  contracts/mirror_mint/src/contract_test.rs
  contracts/mirror_mint/src/migrated_asset_test.rs
  contracts/mirror_mint/src/mock_querier.rs
  contracts/mirror_mint/src/positions.rs
  contracts/mirror_mint/src/positions_test.rs
  contracts/mirror_mint/src/querier.rs
  packages/mirror_protocol/src/collateral_oracle.rs
Labels: enhancement, v2

#34 [Fix] Disable check query when registering collaterals
  artifacts/checksums.txt
  artifacts/mirror_collateral_oracle.wasm
  contracts/mirror_collateral_oracle/src/contract.rs
Labels: bug

#36 [Feature] Auto-staking + add short_reward_weight to PoolInfoResponse
  Cargo.lock
  artifacts/checksums.txt
  artifacts/mirror_staking.wasm
  contracts/mirror_staking/Cargo.toml
  contracts/mirror_staking/schema/handle_msg.json
  contracts/mirror_staking/schema/pool_info_response.json
  contracts/mirror_staking/src/contract.rs
  contracts/mirror_staking/src/contract_test.rs
  contracts/mirror_staking/src/lib.rs
  contracts/mirror_staking/src/migration.rs
  contracts/mirror_staking/src/migration_test.rs
  contracts/mirror_staking/src/mock_querier.rs
  contracts/mirror_staking/src/reward_test.rs
  contracts/mirror_staking/src/rewards.rs
  contracts/mirror_staking/src/staking.rs
  contracts/mirror_staking/src/staking_test.rs
  contracts/mirror_staking/src/state.rs
  packages/mirror_protocol/src/staking.rs
Labels: enhancement, v2

#37 [Feature] Add multiple price sources to collateral oracle
  artifacts/checksums.txt
  artifacts/mirror_collateral_oracle.wasm
  artifacts/mirror_mint.wasm
  contracts/mirror_collateral_oracle/schema/collateral_info_response.json
  contracts/mirror_collateral_oracle/schema/collateral_infos_response.json
  contracts/mirror_collateral_oracle/schema/collateral_price_response.json
  contracts/mirror_collateral_oracle/schema/handle_msg.json
  contracts/mirror_collateral_oracle/src/contract.rs
  contracts/mirror_collateral_oracle/src/mock_querier.rs
  contracts/mirror_collateral_oracle/src/querier.rs
  contracts/mirror_collateral_oracle/src/state.rs
  contracts/mirror_collateral_oracle/src/testing.rs
  contracts/mirror_mint/src/contract.rs
  contracts/mirror_mint/src/contract_test.rs
  contracts/mirror_mint/src/migrated_asset_test.rs
  contracts/mirror_mint/src/mock_querier.rs
  contracts/mirror_mint/src/positions.rs
  contracts/mirror_mint/src/positions_test.rs
  contracts/mirror_mint/src/querier.rs
  packages/mirror_protocol/src/collateral_oracle.rs
Labels: v2

#38 [Feature] Split reward deposit messages into chucks
  artifacts/checksums.txt
  artifacts/mirror_factory.wasm
  contracts/mirror_factory/src/contract.rs
  contracts/mirror_factory/src/testing.rs
Labels: enhancement, v2

#39 [Feature] Change collateral_premium for collateral_multiplier
  artifacts/checksums.txt
  artifacts/mirror_collateral_oracle.wasm
  artifacts/mirror_mint.wasm
  contracts/mirror_collateral_oracle/schema/collateral_info_response.json
  contracts/mirror_collateral_oracle/schema/collateral_infos_response.json
  contracts/mirror_collateral_oracle/schema/collateral_price_response.json
  contracts/mirror_collateral_oracle/schema/handle_msg.json
  contracts/mirror_collateral_oracle/src/contract.rs
  contracts/mirror_collateral_oracle/src/state.rs
  contracts/mirror_collateral_oracle/src/testing.rs
  contracts/mirror_mint/src/contract.rs
  contracts/mirror_mint/src/contract_test.rs
  contracts/mirror_mint/src/migrated_asset_test.rs
  contracts/mirror_mint/src/mock_querier.rs
  contracts/mirror_mint/src/positions.rs
  contracts/mirror_mint/src/positions_test.rs
  contracts/mirror_mint/src/querier.rs
  packages/mirror_protocol/src/collateral_oracle.rs
Labels: enhancement, v2

#42 [Feature] Add anchor market collateral source type
  Cargo.lock
  artifacts/checksums.txt
  artifacts/mirror_collateral_oracle.wasm
  contracts/mirror_collateral_oracle/Cargo.toml
  contracts/mirror_collateral_oracle/schema/handle_msg.json
  contracts/mirror_collateral_oracle/src/mock_querier.rs
  contracts/mirror_collateral_oracle/src/querier.rs
  contracts/mirror_collateral_oracle/src/testing.rs
  packages/mirror_protocol/src/collateral_oracle.rs
Labels: v2

#43 [Feature] Native collateral price source
  Cargo.lock
  artifacts/checksums.txt
  artifacts/mirror_collateral_oracle.wasm
  contracts/mirror_collateral_oracle/Cargo.toml
  contracts/mirror_collateral_oracle/schema/handle_msg.json
  contracts/mirror_collateral_oracle/src/mock_querier.rs
  contracts/mirror_collateral_oracle/src/querier.rs
  contracts/mirror_collateral_oracle/src/testing.rs
  packages/mirror_protocol/src/collateral_oracle.rs
Labels: v2
